apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.mysql.serviceName" . }}
  namespace: {{ include "wordpress.namespace" . }}
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
    - port: {{ .Values.service.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}
