apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.wordpress.serviceName" . }}
  namespace: {{ include "wordpress.namespace" . }}
  labels:
    {{- include "wordpress.wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.wordpress.type }}
  ports:
    - port: {{ .Values.service.wordpress.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wordpress.wordpress.selectorLabels" . | nindent 4 }}
